[project]
name = "visual-trace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Timothy Leung", email = "timothyleung@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.0",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
